books/urls.py
from django.conf.urls import url

from .views import BookDetail, BooksbyPubView, PublishersListView, BooksListView


urlpatterns = [
   url(r'^$', BooksListView.as_view(), name='home'),
   url(r'^books/$', BooksListView.as_view(), name='listofbooks'),
   url(r'^books/(?P<slug>[\w-]+)/$', BookDetail.as_view(), name='book_detail'),
   url(r'^publishers/$', PublishersListView.as_view(), name='publishers'),
   url(r'^publishers/(?P<slug>[\w-]+)/$', BooksbyPubView.as_view(), name='books_by_pub'),
]

campaigns/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from campaigns.views import create_a_campaign, CampaignDetail, CampaignsListView, CampaignUpdate, MyCampaigns


urlpatterns = [
    url(r'^$', login_required(CampaignsListView.as_view()), name='list_of_campaigns'),
    url(r'^create_a_campaign/$', login_required(create_a_campaign), name='create_a_campaign'),
    url(r'^detail/(?P<slug>[\w-]+)/$', login_required(CampaignDetail.as_view()), name='campaign_detail'),
    url(r'^edit/(?P<slug>[\w-]+)/$', login_required(CampaignUpdate.as_view()), name='edit_campaign'),
    url(r'^mycampaigns/(?P<user_id>\d+)/$', login_required(MyCampaigns.as_view()), name='my_campaigns'),
    ]

fund_raiser/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('books.urls', namespace='index')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^customadmin/', include('customadmin.urls', namespace='customadmin')),


    url(r'^accounts/', include('authentication.urls', namespace='accounts')),


    url(r'^', include('books.urls', namespace='books')),

    url(r'^people/', include('people.urls', namespace='people')),

    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),

    url(r'^payment/', include('payment.urls', namespace='paygate')),

    url(r'^contacts/', include('social_feeds.urls', namespace='social')),

    url(r'^invite/', include('contacts.urls', namespace='contacts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from people.models import Person


class Category(models.Model):

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('categories:category_detail', args=[self.id])

    def approved_campaigns(self):
        return self.campaign_set.filter(is_approved=True)


# class Questionaire(models.Model):
#
#     pass


class Campaign(models.Model):
    person = models.ForeignKey(Person)
    category = models.ForeignKey(Category)
    campaign_name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=150, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    target_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    modified = models.DateTimeField(auto_now=True)
    cause = models.TextField()
    image = models.ImageField(upload_to="campaign_covers/",
                              blank=True, null=True)
    is_approved = models.BooleanField(blank=True, default=False)
    donation = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    def __unicode__(self):
        return self.campaign_name

    def get_absolute_url(self):
        return reverse('campaigns:campaign_detail', args=[self.slug])

    def get_edit_url(self):
        return reverse('campaigns:edit_campaign', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.id:
            if not self.slug:
                slug = slugify(self.campaign_name)
                try:
                    obj_with_slug_exits = Campaign.objects.get(slug=slug)
                    if obj_with_slug_exits:
                        self.slug = slug + '_1'
                except Campaign.DoesNotExist:
                    self.slug = slug
        super(Campaign, self).save(*args, **kwargs)


class TeamMember(models.Model):

    name = models.CharField(max_length=200)
    role = models.CharField(max_length=200)
    short_description = models.CharField(max_length=400)
    fb_url = models.URLField()
    campaign = models.ForeignKey(Campaign)

    def __unicode__(self):
        return self.name


class Reward(models.Model):

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    campaign = models.ForeignKey(Campaign)

    def __unicode__(self):
        return self.title


class FundDistribution(models.Model):

    usage = models.CharField(max_length=200)
    allocation = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    campaign = models.ForeignKey(Campaign)

    def __unicode__(self):
        return self.usage

campaigns/forms.py
from django.forms import ModelForm
from campaigns.models import Campaign


class CampaignForm(ModelForm):

    class Meta:
        model = Campaign
        exclude = ('person',
                   'slug',
                   'donation', )


class CampaignUpdateForm(ModelForm):

    class Meta:
        model = Campaign
        exclude = ('slug',
                   'donation', )

campaigns/views.py
import decimal

from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import Q
from django.forms import ValidationError

from people.models import Person
from campaigns.models import (
    Campaign,
    Category,
    Reward,
    FundDistribution,
    TeamMember
)
from campaigns.forms import (
    CampaignForm,
    CampaignUpdateForm,
)


def get_extra_data(post):
    fdd = [k for k in post.keys() if k.startswith('fund-dist-d')]
    fda = [k for k in post.keys() if k.startswith('fund-dist-a')]
    fdd.sort()
    fda.sort()
    tup_fd = [(post[fdd[i]].strip(),
               post[fda[i]].strip()) for i in range(len(fda))]

    rew = [k for k in post.keys() if k.startswith('reward')]
    rew.sort()
    tup_rew = [post[rew[i]].strip() for i in range(len(rew))]

    name = [k for k in post.keys() if k.startswith('name')]
    role = [k for k in post.keys() if k.startswith('role')]
    short_desc = [k for k in post.keys()
                  if k.startswith('short-description')]
    fb_url = [k for k in post.keys() if k.startswith('fb-url')]
    name.sort()
    role.sort()
    short_desc.sort()
    fb_url.sort()
    tup_tm = [(post[name[i]].strip(),
               post[role[i]].strip(),
               post[short_desc[i]].strip(),
               post[fb_url[i]].strip())
              for i in range(len(name))]

    return (tup_fd, tup_rew, tup_tm)


@login_required
def create_a_campaign(request):
    form = CampaignForm()
    if request.method == 'POST':
        form = CampaignForm(request.POST, request.FILES)
        extra_data = get_extra_data(request.POST)
        tup_fd = extra_data[0]
        tup_rew = extra_data[1]
        tup_tm = extra_data[2]
        if form.is_valid():
            person = Person.objects.get(user=request.user)
            cam_obj = form.save(commit=False)
            cam_obj.person = person
            cam_obj.save()
            for each in tup_rew:
                if each:
                    reward = Reward(title=each, campaign=cam_obj)
                    reward.save()
            for each in tup_fd:
                if each[0] and each[1]:
                    fd = FundDistribution(usage=each[0],
                                          allocation=each[1],
                                          campaign=cam_obj)
                    fd.save()
            for each in tup_tm:
                if each[0] and each[1] and each[2] and each[3]:
                    tm = TeamMember(name=each[0],
                                    role=each[1],
                                    short_description=each[2],
                                    fb_url=each[3],
                                    campaign=cam_obj)
                    tm.save()

            return HttpResponseRedirect(
                reverse('campaigns:list_of_campaigns'))
        else:
            form.errors

    return render_to_response('campaigns/create_a_campaign.html',
                              {'form': form,
                               'errors': dict(form.errors.viewitems())},
                              context_instance=RequestContext(request))


class CampaignDetail(generic.DetailView):
    model = Campaign
    template_name = 'campaigns/campaign_detail.html'
    context_object_name = 'campaign'


class CampaignsListView(generic.ListView):
    template_name = 'campaigns/campaigns.html'
    context_object_name = 'campaign_list'
    paginate_by = 10

    def get_queryset(self):
        return Campaign.objects.filter(is_approved=True)

    def get_context_data(self, **kwargs):
        search_results = None
        if self.request.GET:
            search_results = Campaign.objects.filter(
                is_approved=True).filter(Q(
                    campaign_name__icontains=self.request.GET['q']))
        context = super(CampaignsListView, self).get_context_data(**kwargs)
        context['search_results'] = search_results
        return context


class CampaignUpdate(generic.UpdateView):
    model = Campaign
    template_name_suffix = '_update_form'
    form_class = CampaignUpdateForm

    def get_success_url(self):
        return reverse("campaigns:campaign_detail", args=[self.object.slug])

    def post(self, request, *args, **kwargs):
        form = CampaignUpdateForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            extra_data = get_extra_data(form.data)
            cam_obj = Campaign.objects.get(slug=request.META[
                'HTTP_REFERER'].split('/')[-2])
            fd_old = [each.usage
                      for each in cam_obj.funddistribution_set.all()]
            fd_new = [each[0] for each in extra_data[0]]
            fd_to_delete = [each for each in fd_old if each not in fd_new]
            rew_old = [each.title for each in cam_obj.reward_set.all()]
            rew_new = [each for each in extra_data[1]]
            rew_to_delete = [each for each in rew_old if each not in rew_new]
            tm_old = [each.name for each in cam_obj.teammember_set.all()]
            tm_new = [each[0] for each in extra_data[2]]
            tm_to_delete = [each for each in tm_old if each not in tm_new]
            for each in fd_to_delete:
                fd = FundDistribution.objects.get(usage=each, campaign=cam_obj)
                fd.delete()
            for each in rew_to_delete:
                rew = Reward.objects.get(title=each, campaign=cam_obj)
                rew.delete()
            for each in tm_to_delete:
                tm = TeamMember.objects.get(name=each, campaign=cam_obj)
                tm.delete()
            for each in extra_data[1]:
                if each:
                    reward = Reward.objects.get_or_create(title=each,
                                                          campaign=cam_obj)
                    if reward[1]:
                        reward[0].save()
            for each in extra_data[0]:
                if each[0] and each[1]:
                    fd = FundDistribution.objects.get_or_create(
                        usage=each[0],
                        campaign=cam_obj)
                    fd[0].allocation = each[1]
                    fd[0].save()
            for each in extra_data[2]:
                if each[0] and each[1] and each[2] and each[3]:
                    tm = TeamMember.objects.get_or_create(name=each[0],
                                                          campaign=cam_obj)
                    tm[0].role = each[1]
                    tm[0].short_description = each[2]
                    tm[0].fb_url = each[3]
                    try:
                        tm[0].save()
                        tm[0].full_clean()
                    except ValidationError, e:
                        pass
        else:
            form.errors
        return super(CampaignUpdate, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CampaignUpdate, self).get_context_data(**kwargs)
        cam_obj = context['campaign']
        for each in cam_obj.teammember_set.all():
            try:
                each.full_clean()
            except ValidationError, e:
                context['tm_errors'] = [e.message_dict, each.name]
        return context


class MyCampaigns(generic.ListView):
    template_name = 'campaigns/my_campaigns.html'
    context_object_name = 'my_campaigns_list'
    paginate_by = 10

    def get_queryset(self):
        return Campaign.objects.filter(
            person__id__exact=self.kwargs['user_id'])

    def get_context_data(self, **kwargs):
        search_results = None
        if self.request.GET:
            search_results = Campaign.objects.filter(
                is_approved=True).filter(Q(
                    campaign_name__icontains=self.request.GET['q']))
        context = super(MyCampaigns, self).get_context_data(**kwargs)
        context['search_results'] = search_results
        return context


def testpay(request, campaign_id):

    if request.method == 'POST':
        campaign = get_object_or_404(Campaign, id=campaign_id)
        if request.user == campaign.person.user:
            return render(request, 'campaigns/campaign_detail.html', {
                'error_message': 'You cannot donate to your own Campaign',
                'campaign': campaign})
        if campaign:
            campaign.donation += decimal.Decimal(request.POST['donation'])
            campaign.save()
            return HttpResponseRedirect(reverse('campaigns:campaign_detail',
                                                args=[campaign.slug, ]))
    return render(request, 'campaigns/donate.html',
                  {'campaign_id': campaign_id})


class CategoryListView(generic.ListView):
    template_name = 'campaigns/categories.html'
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        return Category.objects.all()

    def get_context_data(self, **kwargs):
        search_results = None
        if self.request.GET:
            search_results = Category.objects.filter(Q(
                campaign_name__icontains=self.request.GET['q']))
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['search_results'] = search_results
        return context


class CategoryDetail(generic.DetailView):
    model = Category
    template_name = 'campaigns/category_detail.html'
    context_object_name = 'category'

campaigns/templates/campaigns/campaign_detail.html
{% extends "base.html" %}
{% block main_title %}Campaigns{% endblock %}
{% block title %}Campaign Detail{% endblock %}
{% block content %}
  {% if user.is_staff and not campaign.is_approved %}
      <a href="{% url 'customadmin:approve' campaign.id %}"><button type="submit" value="{{campaign.id}}"  class="btn btn-primary" >Approve</button></a>
  {% endif %}
<h2>Details of Campaign</h1>
<font color="red"><p>{{ error_message }}</p></font>
  {% if user.profile or user.is_staff %}
    {% ifequal campaign.person.user user  %}  
      <p style="padding-top:10px; padding-left:1000px;"><a href="{{campaign.get_edit_url}}"><button type="submit" value="edit_campaign"  class="btn btn-primary" >Edit Campaign</button></a></p>
      <p>&nbsp;</p>
     {% endifequal %}
  {% endif %} 
  {% if campaign %}
      <table class="table table-hover span10 well" border="0" align="left"  cellpadding="1" cellspacing="1"  width="70%"> 

          <tr><th>Campaign created by</th><td><p>{{campaign.person|capfirst}}</p></td></tr>
          <tr><th>Category</th><td><p>{{campaign.category|capfirst}}</p></td></tr>
          <tr><th>Campaign Name</th><td><p>{{campaign.campaign_name}}</p></td></tr>
          <tr><th>Created</th><td><p>{{campaign.date_created}}</p></td></tr>
          <tr><th>Target Amount</th><td><p>{{campaign.target_amount}}</p></td></tr>
          <tr><th>Total Donation</th><td><p>{{campaign.donation}}</p></td></tr>
          <tr><th>Cause</th><td><p>{{campaign.cause}}</p></td></tr>
          <tr><th rowspan="{{campaign.funddistribution_set.all|length|add:'1'}}">Fund Distribution</th>
            {% for each in campaign.funddistribution_set.all %}
            <tr>
              <td> {{each.usage}} : {{each.allocation}} </td>
            </tr>
            {% endfor %}
          </tr>
          <tr><th rowspan="{{campaign.reward_set.all|length|add:'1'}}">Rewards</th>
            {% for each in campaign.reward_set.all %}
            <tr>
              <td> {{each}} </td>
            </tr>
            {% endfor %}
          </tr>
          <tr><th rowspan="{{campaign.teammember_set.all|length|add:'1'}}">Team members</th>
            {% for each in campaign.teammember_set.all %}
            <tr>
              <td> {{each.name}}, {{each.role}}, {{each.short_description}}, {{each.fb_url}} </td>
            </tr>
            {% endfor %}
          </tr>
          {% if campaign.image %}
              <tr><th>Image</th><td><p><img src="{{campaign.image.url}}" height="300" width="300"></p></td></tr>
          {% else %}
              <tr><th>Image</th><td>No Image Available</td></tr>
          {% endif %}
      </table>
<!--        <p style="padding-top:340px; padding-left:600px;"><a href="{% url 'paygate:ebsindex' campaign.id%}"><button type="submit" value="donate_for_campaign"  class="btn btn-success" >Donate</button></a></p> -->
  {% if user !=  campaign.person.user %}
        <p style="padding-top:340px; padding-left:600px;"><a href="{% url 'campaigns:testpay' campaign.id%}"><button type="submit" value="donate_for_campaign"  class="btn btn-success" >Donate</button></a></p>
  {% endif %}
  {% endif %}
{% endblock %}

campaigns/templates/campaigns/create_a_campaign.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block main_title %}Campaigns{% endblock %}
{% block title %}Create a Campaign{%endblock%}
{% block extrahead %}
 <style type="text/css">
  form.form-horizontal {padding-left: 150px;}
  h4 {padding-top:30px;padding-left: 40px;}
  div.errors {padding-left: 400px;}
  span.help-inline {color:#b94a48;}
  input.required {border:1px solid #b94a48;}
  select.required {border:1px solid #b94a48;}
  textarea.required {border:1px solid #b94a48;}
  </style>

    <script src="{{STATIC_URL}}fundraiser/js/bootbox.min.js"></script>

  <script type="text/javascript">
     $(document).ready(function(){
            $(document).on('focus click keypress keyup change', "input#id_target_amount", 
            function() { $("#total").html($("input#id_target_amount").val()) } );

            var funds=0;
            
            $("#total").html($("input#id_target_amount").val());
            
            $("input[name^='fund-dist-amt']").each(function(){
                if ($.isNumeric($(this).val())) {
                    funds += parseInt($(this).val(),10);
                    if ($(this).is(":hidden")){
                        funds -= parseInt($(this).val(), 10);
                    }
                }
            });
            
            $("#from-fund").html(funds);

			function readURL(input) {
			        if (input.files && input.files[0]) 
			        {
			        	 if (input.files[0].size > 3145728 )
				        	   {
                                  bootbox.alert("Image size should not be greater than 3MB");
                                  // console.log(input.files[0].size);
				        	   }
			        	 else 
			        	   {  
					            var reader = new FileReader();
					            
					            reader.onload = function (e) {
									$('#info_img').attr('src', e.target.result);
									$('.show_man').show();
					                $('#upload_change_image').val('Change Image');
					            }
					            
					            reader.readAsDataURL(input.files[0]);
					       }     
			        }
			    }
		    $("#upload_change_image").change(function(){
		        readURL(this);
		    });
            
            $(document).on('focus click keypress keyup change', "input[name^='fund-dist-a']", display_total_funds);
            
            function display_total_funds (){
                var sum=0;
            if ((parseInt($("input#id_target_amount").val(), 10) == 0.0) || ($("input#id_target_amount").val() == "")) {
                alert("Please enter the target amount first.");
            }
                $("input[name^='fund-dist-amt']").each(function(){
                    if ($.isNumeric($(this).val())) {
                        sum += parseInt($(this).val(),10);
                        if ($(this).is(":hidden"))
                            sum -= parseInt($(this).val(), 10);
                    }
                });
                $("#total").html($("input#id_target_amount").val());
                $("#from-fund").html(sum);
                if (parseInt($("span#total").text()) < parseInt($("span#from-fund").text())) {
                    $("span#errors").html("<strong>&nbsp;&nbsp;You have exceeded your target amount.</strong>");
                }
                else {
                    $("span#errors").html("");
                };
            };	
     });
  </script>

    <script src="{{STATIC_URL}}bootstrap/js/campaign.js"></script>
{% endblock %}
{% block content %}
  <h4>Create a Campaign</h4>
    <p>&nbsp;</p>
  <div>
  <form method="post" action="{% url 'campaigns:create_a_campaign' %}" class="form-horizontal" enctype="multipart/form-data">
     {% csrf_token %}
        <div class="control-group">
            <label class="control-label" for="category">Category</label>
            <div class="controls">{{ form.category }}
                 {% if form.errors.category.0 %}
                        <span class="help-inline" id="required-fields">{{ form.errors.category.0}}</span>
                {% else %}
                            <span class="help-inline" ></span>                
                {% endif %}
            </div>
            
        </div>    	         
		<div class="control-group">
	        <label class="control-label" for="campaign_name">Campaign Name</label>
	        <div class="controls">{{ form.campaign_name }}
	        	 {% if form.errors.campaign_name.0 %}
		            	<span class="help-inline" id="required-fields">{{ form.errors.campaign_name.0}}</span>
                {% else %}
                            <span class="help-inline" ></span>                
	            {% endif %}
	        </div>
            
        </div>        
		<div class="control-group">
	        <label class="control-label" for="target_amount">Target Amount</label>
	        <div class="controls">{{ form.target_amount }}
	        	 {% if form.errors.target_amount.0 %}
		            	<span class="help-inline" id="required-fields">{{ form.errors.target_amount.0}}</span>
                {% else %}
                            <span class="help-inline" ></span>                  
	            {% endif %}
	        </div>
        </div>        

		<div class="control-group">
	        <label class="control-label" for="cause">Cause</label>
	        <div class="controls">{{ form.cause }}
	        	 {% if form.errors.cause.0 %}
		            	<span class="help-inline" id="required-fields">{{ form.errors.cause.0}}</span>
                {% else %}
                            <span class="help-inline" ></span>                  
	            {% endif %}
	        </div>
	    </div>
        <div class="control-group">
            <label class="control-label">Fund Distribution</label>
            <div class="controls">
            <span class="help-inline" id="required-fields"></span>            
                <table class="fund-dist">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Amount</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="row1">
                            <td >
                                <input type="text" value="" name="fund-dist-desc1">
                            </td>
                            <td >
                            <input type="text"  value="" name="fund-dist-amt1">
                            </td>
                            <td>
                                <i class="icon-plus-sign"></i><i class="icon-minus-sign" hidden></i>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Total</label>
            <div class="controls">
               &#8377 <span id="from-fund"></span>/ <span id="total"></span><span id="errors" style="color:#b94a48"></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Rewards</label>
            <div class="controls">
            <span class="help-inline" id="required-fields"></span>            
                <table class="rewards">
                    <tbody>
                        <tr class="row1">
                            <td >
                                <input type="text" value="" name="rewards1">
                            </td>
                            <td>
                                <i class="icon-plus-sign"></i><i class="icon-minus-sign" hidden></i>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Team Members</label>
            <div class="controls">
            <span class="help-inline" id="required-fields"></span>            
                <table class="team-member">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Role</th>
                            <th>Short Description</th>
                            <th>Facebook URL</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="row1">
                            <td >
                                <input type="text" name="name1" value="{{user}}">
                            </td>
                            <td >
                            <input type="text"   name="role1">
                            </td>
                            <td >
                                <input type="text" name="short-description1">
                            </td>
                            <td >
                            <input type="text" name="fb-url1">
                            </td>
                            <td>
                                <i class="icon-plus-sign"></i><i class="icon-minus-sign"></i>
                            </td>
                        </tr>

                    </tbody>
                </table>
        </div>
	    <div class="control-group">
	        <label class="control-label" for="cause">Image</label>
	        <div class="controls">
		        {% render_field form.image placeholder=form.image.label id="upload_change_image" %}
	        </div>
	    </div>
	    <div class="hide show_man" >
	    	<div class="" style="padding-left: 185px;padding-bottom: 50px;padding-top: 20px;"> 
		    	 <img id="info_img" src=""  width="300" height="300">
	    	</div>
	    </div>
        <div class="control-group" >
          <div class="controls">
            <button type="submit" value="submit"  class="btn btn-primary" >Submit</button>
          </div>
        </div>      
  </form>
  </div>
{% endblock %}

campaigns/templates/campaigns/my_campaigns.html
{% extends "base.html" %}
{% block main_title %}Campaigns{% endblock %}
{% block title %}My Campaigns{% endblock %}
{% block content %}
<h2>My Campaigns</h1>
	    <p style="padding-top:10px; padding-left:1000px;"><a href="{% url 'campaigns:create_a_campaign' %}"><button type="submit" value="creat_a_campaign"  class="btn btn-primary" >Create a Campaign</button></a></p>
  <form id="changelist-search" class="form-search" action="." method="get">
    <div class="input-append">
      <label for="searchbar"><img src="{{STATIC_URL}}/images/icon_searchbox.png" alt="Search" /></label>
      <input type="text" class="span2 search-query" name="q" value="" id="searchbar">
      <button type="submit" class="btn btn-primary" value="Search">Search</button>
    </div>
  </form>  
   {% if my_campaigns_list or search_results %} 
   <table class="table table-hover" border="0" align="left"  cellpadding="1" cellspacing="1"  width="70%"> 
       <thead>
         <tr>
             <td>Campaign Name</td>
             <td>Amount</td>
             <td>Created</td>
             <td>Target Completion</td>
             <td>Approved</td>
         </tr>
       </thead>  
       <tbody>
        {% if search_results %}
          {% for campaign in search_results %}
             <tr>
                  <td><a href="{{ campaign.get_absolute_url }}">{{campaign}}</a><br></td>
                  <td>{{campaign.target_amount}}</td>
                  <td>{{campaign.date_created}}</td>
                    <td style="width:30%"><div class="progress"><div class="bar" style="width: {% widthratio campaign.donation campaign.target_amount 100 %}%"></div></div></td>
                    <td>{% if campaign.is_approved %} Yes {% else %} No {% endif %} </td>
             </tr>
          {% endfor %}
        {% else %}
          {% for campaign in my_campaigns_list %}
             <tr>
                  <td><a href="{{ campaign.get_absolute_url }}">{{campaign}}</a><br></td>
                  <td>{{campaign.target_amount}}</td>
                  <td>{{campaign.date_created}}</td>
                    <td style="width:30%"><div class="progress"><div class="bar" style="width: {% widthratio campaign.donation campaign.target_amount 100 %}%"></div></div></td>
                    <td>{% if campaign.is_approved %} Yes {% else %} No {% endif %} </td>
             </tr>
          {% endfor %}        
        {% endif %}          
      </tbody>
   </table>    
      {% if is_paginated %}
          <div class="pagination pull-right">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{% url 'campaigns:my_campaigns' user.person.id %}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{% url 'campaigns:my_campaigns' user.person.id %}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
      {% endif %}
   {% else %} 
     <p>There are no Campaigns</p>
   {% endif %}
{% endblock %}