books/urls.py
from django.conf.urls import url

from .views import BookDetail, BooksbyPubView, PublishersListView, BooksListView


urlpatterns = [
   url(r'^$', BooksListView.as_view(), name='home'),
   url(r'^books/$', BooksListView.as_view(), name='listofbooks'),
   url(r'^books/(?P<slug>[\w-]+)/$', BookDetail.as_view(), name='book_detail'),
   url(r'^publishers/$', PublishersListView.as_view(), name='publishers'),
   url(r'^publishers/(?P<slug>[\w-]+)/$', BooksbyPubView.as_view(), name='books_by_pub'),
]

fund_raiser/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('books.urls', namespace='index')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^customadmin/', include('customadmin.urls', namespace='customadmin')),


    url(r'^accounts/', include('authentication.urls', namespace='accounts')),


    url(r'^', include('books.urls', namespace='books')),

    url(r'^people/', include('people.urls', namespace='people')),

    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),

    url(r'^payment/', include('payment.urls', namespace='paygate')),

    url(r'^contacts/', include('social_feeds.urls', namespace='social')),

    url(r'^invite/', include('contacts.urls', namespace='contacts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_feeds/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from social_feeds.views import invite_gmail_contacts, send_invitation_to_gcontacts

urlpatterns = [
    url(r'^invite_gmail_contacts/$', login_required(invite_gmail_contacts), name='gmail_contacts'),
    url(r'^send_gmail_invitations/$', login_required(send_invitation_to_gcontacts), name='send_invitation_to_gcontacts'),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_feeds/models.py
from django.db import models

# Create your models here.

social_feeds/views.py
import gdata.contacts.service

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from profiles.tasks import massemail
from contacts.utils import google_get_state, google_import


def invite_gmail_contacts(request):
    request.session[settings.GOOGLE_REDIRECT_SESSION_VAR] = request.path
    google_state = google_get_state(request)
    gcs = gdata.contacts.service.ContactsService()
    google_contacts = google_import(request, gcs, cache=True)
    filtered_contacts = []
    if 'q' in request.GET and request.GET['q']:
        search_string = request.GET.get('q', None)
        filtered_contacts = [contact.decode('utf-8')
                             for contact in google_contacts
                             if search_string in contact.decode('utf-8')]
    if filtered_contacts:
        return render_to_response('social_feeds/gmail_contacts.html', {
            'google_state': google_state,
            'google_contacts': filtered_contacts,
        }, context_instance=RequestContext(request))
    else:
        return render_to_response('social_feeds/gmail_contacts.html', {
            'google_state': google_state,
            'google_contacts': google_contacts,
            'filtered_contacts': filtered_contacts
        }, context_instance=RequestContext(request))


def send_invitation_to_gcontacts(request):
    error = True
    if request.method == 'POST':
        if 'invite' in request.POST:
            error = False
            email_list = request.POST.getlist('invite')
            massemail.delay('gmail_invite', 'gm_invite_msg',
                            email_list, request.user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your invitations has been\
                                 sent to the selected users !!!!')
            # return HttpResponseRedirect(reverse('index:home'))
        else:
            error = True
    return render_to_response('social_feeds/invitations_sent.html',
                              {'error': error},
                              context_instance=RequestContext(request))

social_feeds/templates/social_feeds/gmail_contacts.html
{% extends 'base.html' %}
{% load google_contacts %}
{% load fetch_email %}
{% block main_title %}Gmail{% endblock %}
{% block title %}Contacts{% endblock %}
{% block content %}

	<p>
<!--	{% if google_state %}
	  Using imported contacts from Gmail [<a
	  href="{% google_auth_url request %}">stop using</a>]
	{% else %} -->
	  Invite contacts from <a
	  href="{% google_auth_url request %}">Gmail</a>
<!--	{% endif %}  -->
	</p>
	{% if not  google_contacts %}
		<p><b>Note : </b>Fetching contacts of your friends may take sometime</p> 
	{% endif %}

	{% if google_contacts %}
    <h4>Select Contacts</h4>
    <p>&nbsp;</p>
    <form id="changelist-search" class="form-search" action="{% url 'social:gmail_contacts' %}" method="get">
		  <div class="input-append">
		  	<label for="searchbar"><img src="{{MEDIA_URL}}/images/icon_searchbox.png" alt="Search" /></label>
		    <input type="text" class="span2 search-query" name="q" value="" id="searchbar">
		    <button type="submit" class="btn btn-primary" value="Search">Search</button>
		  </div>
	</form>
    <p>
    	  <a href="javascript:" onclick="select()">Select All</a>&nbsp; / &nbsp;
    	  <a href="javascript:" onclick="unselect()" >Unselect All</a>
    	  <a name="Top"></a>
          <a style="padding-left:160px;" href="#Bottom">Go to Bottom</a>
    </p>
	{# <form id="form_check" class="form" action="{% url 'social:send_invitation_to_gcontacts' %}" method="POST"> #}
	<form onsubmit="return atleast_onecheckbox(event)" id="form_check" class="form" action="{% url 'social:send_invitation_to_gcontacts' %}" method="POST">
		{% csrf_token %}
		<div class="row">
         {% for contact in google_contacts %}
		  <div class="span4">
		  	<table class="table">
		  		<tr>
		  			<td>
		  			   <div class="contact_align">	 
		  			    	<input class="select-unselect" id="invite" type="checkbox" name="invite" value="{{contact|fetch_email}}">
				 	  	    {{ contact }}
				 	  </div>	 
				  	</td>  
				  
		  	    </tr>
		  	</table>  
	  	  </div>
	  	  {% endfor %} 	  
		</div>
	  	  <a name="Bottom"></a>
	      <a style="padding-left:320px;" href="#Top">Return to top</a>
		  <p style="padding-top:40px;padding-left:250px;">
		  	  <input type="submit" class="btn btn-primary" value="Send Request"/>
		  	  {# <input type="submit" class="btn btn-primary" value="Send Request" onclick=" return  atleast_onecheckbox()"/> #}
          </p> 	  	  		

	</form>
	{% endif %}
    <script type="text/javascript">
        document.getElementById("searchbar").focus();
        function select(){
			        $('.select-unselect').prop('checked',true);
			        return false;
			    }
        function unselect(){
			        $('.select-unselect').prop('checked',false);
			        return false;
			    }			    
/*		function atleast_onecheckbox()
        { 
         if (document.getElementById('invite').checked) {
            alert('the checkbox is checked');
            }
         else
           {
          alert("please check atleast one..");
          return false;
           }    
        }   	*/

		function atleast_onecheckbox(e) {
		  if ($("input[type=checkbox]:checked").length === 0) {
		      e.preventDefault();
		      alert('Please select a user to invite !!!!');
		      return false;
		  }
		}        		    
    </script>    
{% endblock %}	

social_feeds/templates/social_feeds/invitations_sent.html
{% extends 'base.html' %}
{% block main_title %}Gmail Invitations{% endblock %}
{% block title %}
	{% if error %}
		Not Sent
	{% else %}	
	   Sent
	{% endif %}   
{% endblock %}
{% block content %}
    <h4>Hi, <span>{{request.user.username}}</span></h4>
    <p>&nbsp;</p>
    {% if error %}
        <p>You have not selected any <b>user/email</b> to invite,<br>Please select a user</p>
    {% else %}
	    <!--<p>Invitations has been sent to the selected users !!!!</p>  -->
	    <script>
	        window.close()
	        window.opener.location.href ='{% url "index:home" %}' 
	    </script>
    {% endif %}
    <p>&nbsp;</p>
    <p>Click here to <a href="{% url 'social:gmail_contacts' %}">Invite</a></p>

{% endblock %}	    