books/urls.py
from django.conf.urls import url

from .views import BookDetail, BooksbyPubView, PublishersListView, BooksListView


urlpatterns = [
   url(r'^$', BooksListView.as_view(), name='home'),
   url(r'^books/$', BooksListView.as_view(), name='listofbooks'),
   url(r'^books/(?P<slug>[\w-]+)/$', BookDetail.as_view(), name='book_detail'),
   url(r'^publishers/$', PublishersListView.as_view(), name='publishers'),
   url(r'^publishers/(?P<slug>[\w-]+)/$', BooksbyPubView.as_view(), name='books_by_pub'),
]

fund_raiser/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('books.urls', namespace='index')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^customadmin/', include('customadmin.urls', namespace='customadmin')),


    url(r'^accounts/', include('authentication.urls', namespace='accounts')),


    url(r'^', include('books.urls', namespace='books')),

    url(r'^people/', include('people.urls', namespace='people')),

    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),

    url(r'^payment/', include('payment.urls', namespace='paygate')),

    url(r'^contacts/', include('social_feeds.urls', namespace='social')),

    url(r'^invite/', include('contacts.urls', namespace='contacts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

people/urls.py
from django.conf.urls import url
from django.views.generic import ListView

from people.models import Donor, Beneficiary
from people.views import DonorDetailView, BeneficiaryDetailView


urlpatterns = [
    url(r'^beneficiaries/$', ListView.as_view(template_name='people/beneficiaries.html',
                queryset=Beneficiary.objects.all(), context_object_name='beneficiary_list', paginate_by=10), name='list_of_bnfs'),
    url(r'^beneficiary/detail/(?P<pk>\d+)/$', BeneficiaryDetailView.as_view(), name='beneficiary_detail'),


    url(r'^donors/$', ListView.as_view(template_name='people/donors.html',
                queryset=Donor.objects.all(), context_object_name='donor_list', paginate_by=10), name='list_of_donors'),
    url(r'^donor/detail/(?P<pk>\d+)/$', DonorDetailView.as_view(), name='donor_detail'),
    ]

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Person(models.Model):
    user = models.OneToOneField(User)
    address = models.CharField(max_length=150)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        if self.user.profile.is_beneficiary:
            return reverse('people:beneficiary_detail', args=[self.id])
        else:
            return reverse('people:donor_detail', args=[self.id])

    class Meta:
        abstract = True


class Beneficiary(Person):
    is_approved = models.BooleanField(blank=True, default=False)

    class Meta(Person.Meta):
        verbose_name = "Beneficiary"
        verbose_name_plural = "Beneficiaries"


class Donor(Person):
    pass

people/views.py
from django.views import generic

from people.models import Person


class PersonDetailView(generic.DetailView):
    model = Person
    template_name = 'people/person_detail.html'
    context_object_name = 'person'

people/templates/people/donors.html
{% extends "base.html" %}
{% block main_title %}People{% endblock %}
{% block title %}Donors{%endblock%}
{% block content %}
<h1>Donors</h1>
 <p>&nbsp;</p>
{% if donor_list %}
 <table class="table table-hover " border="0" align="left"  cellpadding="1" cellspacing="1"  width="70%"> 
  {% for donor in donor_list%}
     <tr>
     	<td><a href="{{ donor.get_absolute_url }}">{{donor}}</a></td>
     </tr>
  {% endfor %}
 {% else %}
	 <p>There are no donors</p> 
 {% endif %}
 </table>   
 {% if is_paginated %}
     <div class="pagination pull-right">
         <span class="page-links">
             {% if page_obj.has_previous %}
                 <a href="{% url "people:list_of_donors" %}?page={{ page_obj.previous_page_number }}">previous</a>
             {% endif %}
             <span class="page-current">
                 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
             </span>
             {% if page_obj.has_next %}
                 <a href="{% url "people:list_of_donors" %}?page={{ page_obj.next_page_number }}">next</a>
             {% endif %}
         </span>
     </div>
 {% endif %}
{% endblock %}

people/templates/people/person.html
{% extends "base.html" %}
{% block main_title %}People{% endblock %}
{% block title %}Persons{%endblock%}
{% block content %}
<h1>Persons</h1>
 <p>&nbsp;</p>
{% if person_list %}
 <table class="table table-hover " border="0" align="left"  cellpadding="1" cellspacing="1"  width="70%"> 
  {% for person in person_list%}
     <tr>
     	<td><a href="{{ person.get_absolute_url }}">{{person}}</a></td>
     </tr>
  {% endfor %}
 {% else %}
	 <p>There are no persons</p> 
 {% endif %}
 </table>   
 {% if is_paginated %}
     <div class="pagination pull-right">
         <span class="page-links">
             {% if page_obj.has_previous %}
                 <a href="{% url "people:list_of_persons" %}?page={{ page_obj.previous_page_number }}">previous</a>
             {% endif %}
             <span class="page-current">
                 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
             </span>
             {% if page_obj.has_next %}
                 <a href="{% url "people:list_of_persons" %}?page={{ page_obj.next_page_number }}">next</a>
             {% endif %}
         </span>
     </div>
 {% endif %}
{% endblock %}

people/templates/people/person_detail.html
{% extends "base.html" %}
{% block main_title %}People{% endblock %}
{% block title %}Person Details{% endblock %}
{% block content %}
  <h1>Person Details</h1>
  {% if person %}
	  <table class="table table-hover " border="0" align="left"  cellpadding="1" cellspacing="1"  width="70%"> 
          <tr><td>Person Name :</td><td><p>{{person.user.username}}</p></td></tr>
          <tr><td>Address :</td><td><p>{{person.address}}</p></td></tr>
          <tr><td>Website :</td><td><p>{{person.website}}</p></td></tr>
	    </table>
	{% else %}
	    <p>No details available.</p>
	{% endif %}
  
{% endblock %} 