books/urls.py
from django.conf.urls import url

from .views import BookDetail, BooksbyPubView, PublishersListView, BooksListView


urlpatterns = [
   url(r'^$', BooksListView.as_view(), name='home'),
   url(r'^books/$', BooksListView.as_view(), name='listofbooks'),
   url(r'^books/(?P<slug>[\w-]+)/$', BookDetail.as_view(), name='book_detail'),
   url(r'^publishers/$', PublishersListView.as_view(), name='publishers'),
   url(r'^publishers/(?P<slug>[\w-]+)/$', BooksbyPubView.as_view(), name='books_by_pub'),
]

customadmin/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import approve, UnapprovedUsers, CustomAdminIndex


urlpatterns = [
   url(r'^$', login_required(CustomAdminIndex.as_view()), name='customadmin_index'),
   url(r'^unapproved-users/$', login_required(UnapprovedUsers.as_view()), name='unapproved'),
   url(r'^approve/(?P<user_id>\d+)/$', login_required(login_required(approve)), name='approve'),
]

fund_raiser/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('books.urls', namespace='index')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^customadmin/', include('customadmin.urls', namespace='customadmin')),


    url(r'^accounts/', include('authentication.urls', namespace='accounts')),


    url(r'^', include('books.urls', namespace='books')),

    url(r'^people/', include('people.urls', namespace='people')),

    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),

    url(r'^payment/', include('payment.urls', namespace='paygate')),

    url(r'^contacts/', include('social_feeds.urls', namespace='social')),

    url(r'^invite/', include('contacts.urls', namespace='contacts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customadmin/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404
from django.views.generic import ListView
from django.core.urlresolvers import reverse

from campaigns.models import Campaign
from profiles.tasks import sendemail


def approve(request, campaign_id):
    if request.user.is_staff:
        campaign = get_object_or_404(Campaign, pk=campaign_id)
        campaign.is_approved = True
        campaign.save()
        # sendemail.delay(sub="approve_sub", msg="approve_msg",
        #                 to=campaign.person.user.email,
        #                 user=campaign.person.user)
        return HttpResponseRedirect(reverse('customadmin:unapproved'))
    else:
        raise Http404
    return render_to_response('unapproved_campaigns.html')


class UnapprovedCampaigns(ListView):
    template_name = 'customadmin/unapproved_campaigns.html'
    context_object_name = 'unapproved_campaigns'

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404
        return super(UnapprovedCampaigns, self).get(request, *args, **kwargs)

    def get_queryset(self):
        """
        Returns the unapproved users related to person in
        the database

        """

        return Campaign.objects.filter(is_approved=False)

customadmin/templates/customadmin/customadmin_index.html
{% extends "base.html" %}
{% block main_title %}Admin{% endblock %}
{% block content %}

{% endblock %}

customadmin/templates/customadmin/unapproved_campaigns.html
{% extends "base.html" %}
{% block main_title %}Admin{% endblock %}
{% block title %}Unapproved{%endblock%}
{% block content %}
{% if unapproved_campaigns %}
 <table >
  {% for campaign in unapproved_campaigns%}
     <tr>
     	<td><a href="{% url 'campaigns:campaign_detail' campaign.slug %}">{{ campaign }}</a>&nbsp;&nbsp;&nbsp;&nbsp;</td>
     	{# <td><a href="{% url 'approve' campaign.id %}">Approve</a></td> #}
     	<td><a href="{% url 'customadmin:approve' campaign.id %}"><button type="submit" value="{{campaign.id}}"  class="btn btn-primary" >Approve</button>
     	</a></td>
     </tr>
  {% endfor %}
 {% else %}
	 <p>There are no unapproved Campaigns</p> 
 {% endif %}
 </table>      
{% endblock %}